services:
  - type: web
    name: warisango
    runtime: java
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/warisango-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FIREBASE_CREDENTIALS_LOCATION
        value: file:/etc/secrets/firebase-service-account.json
      - key: FIREBASE_ENABLED
        value: "true"
      - key: YOUTUBE_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false