spring.application.name=warisango

# change the "template" package name to "view"
spring.thymeleaf.prefix=classpath:/view/
spring.thymeleaf.suffix=.html

# API keys
youtube.api.key=AIzaSyBJ4vG75Fx7VVw051QBe8wiUO0x0pv9QZg
youtube.base.url=https://www.googleapis.com/youtube/v3

# Thymeleaf templates are located in src/main/resources/view/
spring.thymeleaf.prefix=classpath:/view/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
