package com.warisango.service;

import com.google.genai.Client;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Schema;
import com.google.genai.types.Type;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.warisango.dto.AIExtractionResponse;
import com.warisango.exception.AIProcessingException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * Extracts structured heritage business information from transcripts
 * using Google's Gemini API.
 */
@Service
public class AIExtractionService {

    private static final Logger logger =
            LoggerFactory.getLogger(AIExtractionService.class);

    private final Client geminiClient;

    private final ObjectMapper objectMapper;

    private final String model;

    /**
     * Creates the AI extraction service.
     *
     * @param apiKey Gemini API key
     * @param model Gemini model name
     * @param objectMapper Jackson object mapper
     */
    public AIExtractionService(
            @Value("${gemini.api.key}") String apiKey,
            @Value("${gemini.model}") String model,
            ObjectMapper objectMapper) {

        this.geminiClient = Client.builder()
                .apiKey(apiKey)
                .build();

        this.objectMapper = objectMapper;
        this.model = model;
    }

    /**
     * Extracts heritage business information from a transcript.
     *
     * @param transcript transcript generated by AssemblyAI
     * @return structured heritage information
     */
    public AIExtractionResponse extract(String transcript) {

        validateTranscript(transcript);

        try {

            String prompt = buildPrompt(transcript);

            GenerateContentConfig config =
                    GenerateContentConfig.builder()
                            .responseMimeType("application/json")
                            .responseSchema(buildResponseSchema())
                            .temperature(0.0f)
                            .build();

            GenerateContentResponse response =
                    geminiClient.models.generateContent(
                            model,
                            prompt,
                            config
                    );

            String jsonResponse = response.text();

            if (jsonResponse == null || jsonResponse.isBlank()) {

                throw new AIProcessingException(
                        "Gemini returned an empty extraction result."
                );
            }

            logger.info(
                    "Heritage information extracted successfully."
            );

            return objectMapper.readValue(
                    jsonResponse,
                    AIExtractionResponse.class
            );

        } catch (AIProcessingException exception) {

            throw exception;

        } catch (Exception exception) {

            logger.error(
                    "Failed to extract heritage information using Gemini.",
                    exception
            );

            throw new AIProcessingException(
                    "AI extraction failed.",
                    exception
            );
        }
    }

    /**
     * Builds the extraction prompt.
     *
     * @param transcript transcript text
     * @return extraction prompt
     */
    private String buildPrompt(String transcript) {

        return """
                You are a heritage food information extraction system
                for WarisanGo, a Malaysian heritage food discovery platform.

                Extract information from the transcript provided below.

                You allow do some research from outside sources to find the 
                information if it is not explicitly mentioned in the transcript.

                Extract these seven fields:

                1. name
                   The name of the food business, restaurant, shop,
                   stall, or heritage food establishment.

                2. address
                   The complete street or physical address if mentioned.

                3. state
                   The Malaysian state or federal territory if mentioned.

                4. city
                   The city if mentioned.

                5. location
                   The geographical location if explicitly mentioned.
                   This can contain latitude and longitude if available,
                   otherwise use the location description.
                   Do not guess coordinates.

                6. description
                   A concise description of the business and its
                   heritage significance based only on the transcript.

                7. operatingHour
                   The operating hours if explicitly mentioned.


                TRANSCRIPT:

                ---
                %s
                ---
                """.formatted(transcript);
    }

    /**
     * Defines the JSON schema expected from Gemini.
     *
     * @return Gemini response schema
     */
    private Schema buildResponseSchema() {

        Schema nullableString = Schema.builder()
                .type("STRING")
                .build();

        return Schema.builder()
                .type("OBJECT")
                .properties(
                        Map.of(
                                "name", nullableString,
                                "address", nullableString,
                                "state", nullableString,
                                "city", nullableString,
                                "location", nullableString,
                                "description", nullableString,
                                "operatingHour", nullableString
                        )
                )
                .required(
                        List.of(
                                "name",
                                "address",
                                "state",
                                "city",
                                "location",
                                "description",
                                "operatingHour"
                        )
                )
                .build();
    }

    /**
     * Validates the transcript before sending it to Gemini.
     *
     * @param transcript transcript text
     */
    private void validateTranscript(String transcript) {

        if (transcript == null || transcript.isBlank()) {

            throw new AIProcessingException(
                    "Transcript cannot be empty."
            );
        }
    }
}